import { ARCHETYPES, PROMPTS, type Prompt } from '@/data/prompts';
export type AnswerValue = 0 | 1 | 2 | 3;
export type Answer = { promptId: string; reactionMs: number; choice: AnswerValue };
export type Result = { id: string; seed: string; score: number; archetype: (typeof ARCHETYPES)[number]; title: string; summary: string; shareCopy: string[]; prompts: Prompt[]; challengeUrl: string; noindex: boolean };
export function hashSeed(input: string): number { let hash = 2166136261; for (const char of input) { hash ^= char.charCodeAt(0); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
export function pickPrompts(seed: string, count = 6): Prompt[] { const pool = [...PROMPTS]; const picks: Prompt[] = []; let state = hashSeed(seed); while (picks.length < count && pool.length > 0) { state = Math.imul(state ^ 0x9e3779b9, 1103515245) >>> 0; const index = state % pool.length; picks.push(pool.splice(index, 1)[0]); } return picks; }
export function dailySeed(date = new Date()): string { return date.toISOString().slice(0, 10); }
export function normaliseReaction(reactionMs: number): number { const capped = Math.max(120, Math.min(1400, reactionMs)); return Math.round(((1400 - capped) / 1280) * 100); }
export function scoreAnswers(answers: Answer[], seed: string): number { const prompts = pickPrompts(seed, answers.length || 6); const totalWeight = prompts.reduce((sum, prompt) => sum + prompt.weight, 0); const raw = answers.reduce((sum, answer, index) => { const prompt = prompts[index] ?? prompts[0]; const timing = normaliseReaction(answer.reactionMs); const choiceBonus = [0, 7, 13, 17][answer.choice] ?? 0; return sum + (timing + choiceBonus) * prompt.weight; }, 0); const scaled = totalWeight === 0 ? 67 : Math.round(raw / totalWeight); return Math.max(7, Math.min(100, scaled)); }
export function archetypeForScore(score: number): (typeof ARCHETYPES)[number] { if (score >= 88) return ARCHETYPES[0]; if (score >= 76) return ARCHETYPES[1]; if (score >= 62) return ARCHETYPES[3]; if (score >= 48) return ARCHETYPES[5]; if (score >= 34) return ARCHETYPES[4]; return ARCHETYPES[2]; }
export function slugify(text: string): string { return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 48) || '67speed'; }
export function resultIdFromSeed(seed: string, score: number, archetype: string): string { const hash = hashSeed(`${seed}:${score}:${archetype}`).toString(36).slice(0, 6); return `${slugify(archetype)}-${score}-${hash}`; }
export function createResult(seed: string, answers: Answer[]): Result { const prompts = pickPrompts(seed, 6); const score = scoreAnswers(answers, seed); const archetype = archetypeForScore(score); const id = resultIdFromSeed(seed, score, archetype); const title = `67 Speed: ${score}/100`; const summary = `${archetype}. You handled the nonsense like you were born in the group chat.`; const challengeUrl = `/start/?seed=${encodeURIComponent(seed)}&challenge=${id}`; const shareCopy = [`My 67 Speed is ${score}/100 — ${archetype}.`,`I survived the 6.7-second nonsense test. Barely.`,`Try it at 67speed.com${challengeUrl}`]; return { id, seed, score, archetype, title, summary, shareCopy, prompts, challengeUrl, noindex: true }; }
export function resultFromId(resultId: string): Result { const parts = resultId.split('-'); const score = Number(parts.at(-2) ?? 67); const archetype = ARCHETYPES.find((item) => slugify(item) === parts.slice(0, -2).join('-')) ?? archetypeForScore(score); const seed = parts.at(-1) ?? '67seed'; return createResult(seed, pickPrompts(seed, 6).map((prompt, index) => ({ promptId: prompt.id, reactionMs: 420 + index * 50, choice: (index % 4) as AnswerValue }))); }
